use_frameworks!

target 'ICAEquipmentModelType_Example' do
  pod 'ICAEquipmentModelType', :path => '../'

  target 'ICAEquipmentModelType_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
