//
//  ICAEquipmentENLocaliseString.swift
//  Pods
//
//  Created by Wahyu Sumartha on 05/09/2017.
//
//

import Foundation

struct ICAEquipmentENLocaliseString: ICAEquipmentLocaliseStringType {
  let sunroof: String = "Sunroof"
  let sunroofElectric: String = "Sunroof Electric"
  let alloyWheel: String = "Velg Racing"
  let hidHeadlight: String = "Hid Headlight"
  let hidHeadlightAl: String = "Hid Headlight Al"
  let frontFoglight: String = "Front Foglight"
  let rearFoglight: String = "Rear Foglight"
  let powerMirror: String = "Power Mirror"
  let powerMirrorFold: String = "Power Mirror Fold"
  let sunvisorVM: String = "Sunvisor VM"
  let sideMirrorLight: String = "Side Mirror Light"
  let rainSensingWiper: String = "Rain Sensing Wiper"
  let airCondition: String = "Air Condition"
  let climateControl: String = "Climate Control"
  let climateControl4z: String = "Climate Control 4z"
  let cruiseControl: String = "Cruise Control"
  let paddleShiftControl: String = "Paddle Shift Control"
  let tiltTeleSteering: String = "Tilt Tele Steering"
  let seatHeightAdjuster: String = "Seat Height Adjuster"
  let powerSteering: String = "Power Steering"
  let powerSteeringRs: String = "Power Steering Rs"
  let usbAux: String = "USB Aux"
  let powerDriverSeat: String = "Power Driver Seat"
  let powerPassengerSeat: String = "Power Passenger Seat"
  let leatherSeat: String = "Leather Seat"
  let leatherSteering: String = "Leather Steering"
  let splitFoldRearSeat: String = "Split Fold Rear Seat"
  let driverAirbag: String = "Driver Airbag"
  let passengerAirbag: String = "Passenger Airbag"
  let sideAirbag: String = "Side Airbag"
  let sideAirbagDs: String = "Side Airbag DS"
  let curtainAirbag: String = "Curtain Airbag"
  let keylessEntry: String = "Keyless Entry"
  let abs: String = "ABS"
  let tiptronic: String = "Tiptronic"
  let bodykit: String = "Bodykit"
  let dvd: String = "DVD"
  let tv: String = "TV"
  let facelift: String = "Facelift"
  let mFuncSteering: String = "M Func Steering"
  let memorySeatsRear: String = "Memory Seats Rear"
  let originalPaint: String = "Original Paint"
  let originalPaintSS: String = "Original Paint SS"
  let originalPaintMetallic: String = "Original Paint Metallic"
  let panoramicRoof: String = "Panoramic Roof"
  let parkAssist: String = "Park Assist"
  let reverseSensors: String = "Reverse Sensors"
  let powerBoot: String = "Power Boot"
  let vacuumDoor: String = "Vacuum Door"
  let seatBeltPretensioner: String = "Seat Belt Pretensioner"
  let stability: String = "Stability"
  let traction: String = "Traction"
  let remoteLocking: String = "Remote Locking"
  let alarmImmobilizer: String = "Alarm Immobilizer"
  let radio: String = "Radio"
  let usbIPod: String = "USB IPod"
  let aux: String = "AUX"
  let bluetooth: String = "Bluetooth"
  let cd: String = "CD"
  let panoramicRoofElectric: String = "Panoramic Roof Electric"
  let electricSteering: String = "Electric Steering"
  let startButton: String = "Start Button"
}
