//
//  ICAEquipmentTHLocaliseString.swift
//  Pods
//
//  Created by Wahyu Sumartha on 05/09/2017.
//
//

import Foundation

struct ICAEquipmentTHLocaliseString: ICAEquipmentLocaliseStringType {
  let sunroof: String = "ซันรูฟ"
  let sunroofElectric: String = "ซันรูฟไฟฟ้า"
  let alloyWheel: String = "Velg Racing"
  let hidHeadlight: String = "ไฟหน้า Hid"
  let hidHeadlightAl: String = "หน้า Hid AI"
  let frontFoglight: String = "ไฟตัดหมอกหน้า"
  let rearFoglight: String = "ไฟตัดหมอกหลัง"
  let powerMirror: String = "กระจกไฟฟ้า"
  let powerMirrorFold: String = "กระจกมองข้างพับไฟฟ้า"
  let sunvisorVM: String = "ที่บังแดด"
  let sideMirrorLight: String = "ไฟเลี้ยวที่กระจกมองข้าง"
  let rainSensingWiper: String = "ระบบปัดน้ำฝนอัตโนมัติ"
  let airCondition: String = "เครื่องปรับอากาศ"
  let climateControl: String = "Climate Control"
  let climateControl4z: String = "Climate Control 4z"
  let cruiseControl: String = "ระบบควบคุมความเร็วอัตโนมัติ"
  let paddleShiftControl: String = "ระบบควบคุมการเปลี่ยนเกียร์ที่พวงมาลัย"
  let tiltTeleSteering: String = "Tilt Tele Steering"
  let seatHeightAdjuster: String = "เบาะปรับสูงต่ำ"
  let powerSteering: String = "พวงมาลัยพาวเวอร์"
  let powerSteeringRs: String = "พวงมาลัยพาวเวอร์"
  let usbAux: String = "USB Aux"
  let powerDriverSeat: String = "เบาะคนขับปรับไฟฟ้า"
  let powerPassengerSeat: String = "เบาะผู้โดยสารปรับไฟฟ้า"
  let leatherSeat: String = "เบาะหนัง"
  let leatherSteering: String = "พวมาลัยหุ้มหนัง"
  let splitFoldRearSeat: String = "เบาะหลังแยกพับ"
  let driverAirbag: String = "ถุงลมนิรภัยฝั่งคนขับ"
  let passengerAirbag: String = "ถุงลมนิรภัยฝั่งผู้โดยสาร"
  let sideAirbag: String = "ถุงลมนิรภัยด้านข้าง"
  let sideAirbagDs: String = "ถุงลมนิรภัยด้านข้าง"
  let curtainAirbag: String = "ม่านถุงลมนิรภัย"
  let keylessEntry: String = "ระบบกุญแจ"
  let abs: String = "ABS"
  let tiptronic: String = "Tiptronic"
  let bodykit: String = "ชุดแต่งสำเร็จรูป"
  let dvd: String = "DVD"
  let tv: String = "TV"
  let facelift: String = "Facelift"
  let mFuncSteering: String = "พวงมาลัยมัลติฟังก์ชั่น"
  let memorySeatsRear: String = "เบาะหลังไฟฟ้า Memory"
  let originalPaint: String = "สีเดิม"
  let originalPaintSS: String = "สีเดิม"
  let originalPaintMetallic: String = "สีเมทัลลิคเดิม"
  let panoramicRoof: String = "หลังคาแก้ว"
  let parkAssist: String = "ระบบช่วยจอด"
  let reverseSensors: String = "เซนเซอร์ถอยหลัง"
  let powerBoot: String = "Power Boot"
  let vacuumDoor: String = "ประตูดูด"
  let seatBeltPretensioner: String = "Seat Belt Pretensioner"
  let stability: String = "Stability"
  let traction: String = "Traction"
  let remoteLocking: String = "รีโมทล๊อค"
  let alarmImmobilizer: String = "กุญแจอัจฉริยะ"
  let radio: String = "วิทยุ"
  let usbIPod: String = "USB IPod"
  let aux: String = "AUX"
  let bluetooth: String = "Bluetooth"
  let cd: String = "CD"
  let panoramicRoofElectric: String = "Panoramic Roof Electric"
  let electricSteering: String = "พวงมาลัยไฟฟ้า"
  let startButton: String = "ปุ่ม Start"
}
